### ISSUE TITLE
Please add releases

### ISSUE THREAD

**Issue by sk7725** [Sonnicon/mindustry-newhorizons#1]
Please add releases and jars on the releases for easy mod enjoying!
![image](https://user-images.githubusercontent.com/58885089/102944372-eab3d200-44fd-11eb-8f99-f17a36360f61.png)

**Comment by Sonnicon** [comment]
The mod is extremely unfinished and I would not yet even consider it representative of the final goal. When I am closer to a playable state, I will be doing this.If you still wish to use what is currently done, you can find build artifacts in [Github Actions](https://github.com/Sonnicon/mindustry-newhorizons/actions).
Thank you, closed.
